[[significant-terms]]
== 信息聚合之显著项

`significant_terms` （SigTerms）聚合((("significant_terms aggregation")))((("aggregations", "Significant Terms"))) 与其他聚合都不相同。
目前为止我们看到的所有聚合在本质上都是简单的数学计算。将不同这些构造块相互组合在一起，我们可以创建复杂的聚合以及数据报表。

`significant_terms` 有着不同的工作机制。对有些人来说，它甚至看起来有点像机器学习。((("terms", "uncommonly common, finding with SigTerms aggregation"))) `significant_terms` 聚合可以找到数据集中 _不寻常_ 的常用项。

什么是 _不普通的共同_ ？这些项从统计上看是不寻常的，数据出现的频率会超过后台建议的比例。
这些统计上的异常通常象征着数据里的某些有趣信息。

例如，假设我们负责探测跟踪信用卡欺诈，客户打电话过来抱怨他们信用卡出现异常交易，它们的帐户遭受到危害。这些交易信息只是更严重问题的症状。在过去，商户要么不知道客户的信用卡信息被盗，要么根本就不知道它们正遭受危害。

我们的任务是找到 _危害的共同点_ ，如果我们有 100 个客户抱怨交易异常，他们很有可能都属于同一个商户，而这家商户有可能就是罪魁祸首。

当然，比仅是找到客户共同商户还能做的更好。例如，很多客户在它们近期交易历史记录中会有很大的商户如亚马逊，我们可以将亚马逊排除在外，因为有很多未受危害的信用卡的近期交易商户也都有亚马逊。

这是一个 _普通的共同_ 商户的例子。每个人都共享这个商户，无论有没有遭受危害。我们对它并不感兴趣。

在另一个极端情况下，我们有一些很小商户比如街角的一家药店，它们属于 _普通但不寻常_ 的情况，只有一两个客户有交易记录。我们同样可以将这些商户排除，因为所有受到危害的信用卡都没有与这些商户发生过交易，我们可以肯定它们不是安全漏洞的责任方。

我们真正想要的是 _不普通的共同_ 商户。所有受到危害的信用卡都与它们发生过交易，但是在未受危害的背景噪声下，它们并不明显。这些商户属于统计异常，它们比应该出现的频率要高。这些不普通的共同商户很有可能就是需要调查的。

`significant_terms` 聚合就是做这些事情。它分析数据，找出那些与大量背景数据相比出现频率统计异常的项。

我们拿统计异常 _做什么_ 取决于数据本身。 对于信用卡数据，我们可能会想找出信用卡欺诈。
对于电商数据，我们可能会想找出未被识别的人口信息，从而进行更高效的市场推广。
如果我们正在分析日志，我们可能会发现一个服务器会抛出比它本应抛出的更多异常。 `significant_terms` 的应用还远不止这些。
